### PR TITLE
FIX: #106 - cursor position

### PR DESCRIPTION
**Pull request by nichoth**
The example in the repo only works if the canvas is located at `0, 0`. This looks like the simplest way to fix.

### CODE REVIEW

**Comment by jakubfiala** [comment]
hey @nichoth, apologies for the silence from my side, i've been really busy the last few days but will try to get to reviewing this next week.

**Comment by jakubfiala** [comment]
@nichoth thank you for the PR submission! I had a look and as far as I understand, you are using the canvas' bounding rectangle to find the X/Y offset of the cursor _within_ the element. However, this is what the `offsetX/Y` properties are already doing (see [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX)). The `pointermove` event is attached to the canvas element [here](https://github.com/jakubfiala/atrament/blob/main/src/pointer-events.js#L23). This means that `offsetX/Y` should refer to the cursor's offset from the "padding edge" of the canvas, which essentially means its top left corner.

I think in this case Atrament is already doing the right thing, though I'm open to be proven otherwise.

The other concern would be calling `getBoundingClientRect` every time the pointer moves. Calling this method is known to trigger [browser reflow](https://developers.google.com/speed/docs/insights/browser-reflow) so it shouldn't be called very often. As mentioned, in this case relying on the built in properties of the `MouseEvent` should suffice.

Hope that makes sense, sorry to reject the PR! Feel free to reopen if you'd like to discuss it further. And thanks again for the contribution!

**Comment by nichoth** [comment]
I will try adding a screen recording to github so that we are seeing the same thing.

This is at [tag 4.3.5](https://github.com/bicycle-codes/atrament/tree/1d6b361fe1bc49ffad4525d553267d6dfa9dac7c).

The offset of the line that is drawn looks like about the same as the margin on the top and left of the canvas element.

https://github.com/user-attachments/assets/fefd4d2c-6f42-4fa0-a196-857df0e7f4f0

**Comment by nichoth** [comment]
I will try adding a screen recording to github so that we are seeing the same thing.

This is at [tag 4.3.5](https://github.com/bicycle-codes/atrament/tree/1d6b361fe1bc49ffad4525d553267d6dfa9dac7c).

The offset of the line that is drawn looks like about the same as the margin on the top and left of the canvas element.


https://github.com/user-attachments/assets/8e064171-ed12-4dfb-9feb-2b8d7e5ddfc1

**Comment by jakubfiala** [comment]
@nichoth that's really odd. I cannot replicate this behaviour anywhere incl. the high-DPR devices I have. Like I mentioned, `offsetX/Y` should always be relative to the top left edge of the canvas element, not the whole document. I really do think this is a CSS issue. If you're still struggling with the issue, I'd be happy to schedule a quick call to debug it together. Feel free to email me at studio@fiala.space and we can arrange a time.

**Comment by nichoth** [comment]
That is odd that you are not able to reproduce it. My tasks have changed since I created this issue actually, and I do not have bandwidth to look into it further. It will have to remain a mystery. Thank you for the offer to debug it, though.

**Pull request closed without merging**
